# Exported from:        http://host.docker.internal:5516/
# Release version:      24.3.5
# Date created:         Thu Mar 06 19:54:56 GMT 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_Onboard to Deploy.yaml
