# Exported from:        http://host.docker.internal:5516/
# Release version:      24.3.5
# Date created:         Thu Mar 06 19:54:56 GMT 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Acme DEV/Onboarding
spec:
- template: Onboard to Deploy
  scheduledStartDate: 2025-03-06T08:00:00Z
  phases:
  - phase: New Phase
    tasks:
    - name: My first deployment
      type: xldeploy.Deploy
      deploymentPackage: my-app/1.0
      deploymentEnvironment: dev
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
      precondition: "not ${test-release}"
      variableMapping:
        pythonScript.server: "${folder.deploy-server}"
    color: "#3d6c9e"
  variables:
  - type: xlrelease.BooleanVariable
    key: test-release
    requiresValue: false
    showOnReleaseStart: false
    label: Test Release
    description: "If enabled, no deployments will take place"
    value: true
  riskProfile: Default risk profile
  author: admin
