apiVersion: xl-release/v1
kind: Templates
spec:
  - type: xlrelease.ThemeSettings
    id: Configuration/settings/ThemeSettings
    headerName: GitOps Example
    headerAccentColor: ORANGE
    description: Instance for testing GitOps scenarios with Release
    loginMessage: |-
      Digital.ai Release GitOps Test Environment
      Use this server to test folder promotion with GitOps
